### ISSUE TITLE
openssh_cert: Make it possible to use a signing key stored in ssh-agent

### ISSUE THREAD

**Issue by dougstanley** [ansible-collections/community.crypto#116]
##### SUMMARY
If the ssh signing key is password protected, and the user has it unlocked in an ssh-agent, an additional flag needs to be passed to ssh-keygen in order for it to use the key from the agent when signing. I propose an additional optional module boolean argument to add the flag needed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssh_cert.py

##### ADDITIONAL INFORMATION
See summary.

```yaml
- openssh_cert:
    type: user
    signing_key: /path/to/private_key
    use_agent: yes
    public_key: /path/to/public_key.pub
    path: /path/to/certificate
    valid_from: always
    valid_to: forever
```
