### ISSUE TITLE
Can't use acme_certificate/account_key_content in ansible-vault

### ISSUE THREAD

**Issue by x70b1** [ansible-collections/community.crypto#122]
##### SUMMARY

First of all I like the aproach to use ansible as acme client.
Unfortunately I can't store my private account key in an ansible-vault var.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
I used the stuff around `acme_*`.

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/x70b1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### STEPS TO REPRODUCE

I will use `acme_account` here to create a new account. I have seen the problem on all other acme parts too. 
The following task works. I created a RSA key, replaced all line breaks with `\n` and included it as one line at `account_key_content`. The example has a shortened line.

```yaml
    - name: "Create my account"
      community.crypto.acme_account:
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        account_key_content: "-----BEGIN RSA PRIVATE KEY-----\nMIIJKQ .......... DQkKX\n-----END RSA PRIVATE KEY-----\n"
        state: present
        terms_agreed: yes
        contact:
          - mailto:mail@example.com
```

After that was working I wanted to move it to my vault. The new task is: 

```yaml
    - name: "Create my account"
      community.crypto.acme_account:
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        account_key_content: "{{ vault_letsencrypt_key }}"
        state: present
        terms_agreed: yes
        contact:
          - mailto:mail@example.com
```

My specific vault file:

```
vault_letsencrypt_key: -----BEGIN RSA PRIVATE KEY-----\nMIIJKQ ......
```

##### EXPECTED RESULTS

It should work. I know that I could also encrypt the RSA key as file (I have not tested this yet). 

##### ACTUAL RESULTS

I got ` msg: error while parsing account key: error while loading key: Could not deserialize key data.`.
