### ISSUE TITLE
openssl_privatekey does not recreate keys

### ISSUE THREAD

**Issue by x70b1** [ansible-collections/community.crypto#124]
##### SUMMARY

A key generated with `openssl_privatekey` is not regenerated if I change the type.

My idea was that Ansible should make sure that a key is in the given state. But this is not happening.
As you can see I create a RSA 4096 bit key as thats are the defaults. After a change to an ECC key Ansible changes nothing.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

 `openssl_privatekey`

##### ADDITIONAL INFORMATION
```yaml
    - name: generate key
      community.crypto.openssl_privatekey:
        path: /my/privatekey.key

    - name: change key
      community.crypto.openssl_privatekey:
        path: /my/privatekey.key
        type: ECC
        curve: secp384r1
```
