### ISSUE TITLE
Out of memory error when attempting to create luks2 device

### ISSUE THREAD

**Issue by aryan-gupta** [ansible-collections/community.crypto#136]
##### SUMMARY
An error occurs when using luks2 type when creating a crypt device

Actual code snippet (minimal example later):
task:
``` yaml
- name: Create keyfile for luks
  shell: "openssl rand -base64 {{ item.keyfile_len }} | tr -d '\n' | tee {{ item.keyfile }}"
  with_items: "{{ crypt }}"

- name: Setup luks partitions
  community.crypto.luks_device:
    device: "{{ item.device }}"
    state: "opened"
    name: "{{ item.name }}"
    # label: "{{ item.name }}"
    type: "{{ item.type }}"
    cipher: "{{ item.cipher }}"
    keysize: "{{ item.keysize }}"
    hash: "{{ item.hash }}"
    keyfile: "{{ item.keyfile }}"
    #passphrase: "{{ item.passphrase }}"
  with_items: "{{ crypt }}"

- name: Add luks passprase
  community.crypto.luks_device:
    device: "{{ item.device }}"
    keyfile: "{{ item.keyfile }}"
    new_passphrase: "{{ item.passphrase }}"
  with_items: "{{ crypt }}"
```

vars:
``` yaml
crypt:
  - device: /dev/vda2
    name: "{{ crypt_name }}"
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha512
    passphrase: "{{ luks_password }}"
    keyfile: "/tmp/{{ crypt_name }}_{{ ansible_date_time.date }}"
    keyfile_len: 512
```

Error:
![image](https://user-images.githubusercontent.com/12296130/97946206-b589cf80-1d57-11eb-8218-5f22ff58444a.png)

Note that the key never gets added
![image](https://user-images.githubusercontent.com/12296130/97946262-e1a55080-1d57-11eb-99bb-994fb6695ac8.png)

Replacing `luks2` with `luks1` maks it work again (note that I ctrl+c after the playbook got past the adding of passcode)
![image](https://user-images.githubusercontent.com/12296130/97946366-3d6fd980-1d58-11eb-8ffb-642464560dd4.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.crypto.luks_device

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /root/a/0/ansible-linux/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/root/a/0/ansible-linux/ansible.cfg) = ['/root/a/0/ansible-linux/localhost']
```

##### OS / ENVIRONMENT
OS: Arch Linux install iso: archlinux-2020.10.01-x86_64.iso
Machine: libvirt/kvm/qemu VM

##### STEPS TO REPRODUCE
When attempting to run this ansible-playbook code (minimal code)

``` yaml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Setup luks partitions
      community.crypto.luks_device:
        device: "/dev/vda"
        state: "present"
        name: "test"
        type: luks2
        passphrase: "123"
```

I get an out of memory error. Attempted multiple times and the same error occurs.
![image](https://user-images.githubusercontent.com/12296130/97946736-44e3b280-1d59-11eb-9a31-4aab10ee3287.png)

If `type:` is replaced with luks1, the error disappears. 
``` yaml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Setup luks partitions
      community.crypto.luks_device:
        device: "/dev/vda"
        state: "present"
        name: "test"
        type: luks1
        passphrase: "123"
```
![image](https://user-images.githubusercontent.com/12296130/97946612-fc2bf980-1d58-11eb-87c9-c99070531a60.png)

##### EXPECTED RESULTS
crypt device should be created with luks2 header format

##### ACTUAL RESULTS
`cryptsetup` starts but gets killed because of an out of memory error. Running `cryptsetup` manually works without any issues.

![image](https://user-images.githubusercontent.com/12296130/97946958-cb988f80-1d59-11eb-82af-33f660150d48.png)

![image](https://user-images.githubusercontent.com/12296130/97946981-e539d700-1d59-11eb-8dcc-443071335082.png)

output of -vvv
```
ansible-playbook 2.10.2
  config file = /root/a/0/ansible-linux/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
Using /root/a/0/ansible-linux/ansible.cfg as config file
host_list declined parsing /root/a/0/ansible-linux/localhost as it did not pass its verify_file() method
script declined parsing /root/a/0/ansible-linux/localhost as it did not pass its verify_file() method
auto declined parsing /root/a/0/ansible-linux/localhost as it did not pass its verify_file() method
Parsed /root/a/0/ansible-linux/localhost inventory source with ini plugin

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
task path: /root/a/0/ansible-linux/test.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539 `" && echo ansible-tmp-1604373915.8610246-7734-152505809239539="` echo /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<localhost> Python interpreter discovery fallback (unable to get Linux distribution/version info)
Using module file /usr/lib/python3.8/site-packages/ansible/modules/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-77303wte3qvg/tmp1j33jo_s TO /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539/ /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1604373915.8610246-7734-152505809239539/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Setup luks partitions] ***************************************************
task path: /root/a/0/ansible-linux/test.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824 `" && echo ansible-tmp-1604373917.1401203-7799-221460709672824="` echo /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824 `" ) && sleep 0'
Using module file /usr/lib/python3.8/site-packages/ansible_collections/community/crypto/plugins/modules/luks_device.py
<localhost> PUT /root/.ansible/tmp/ansible-local-77303wte3qvg/tmpztewcmh_ TO /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824/AnsiballZ_luks_device.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824/ /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824/AnsiballZ_luks_device.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824/AnsiballZ_luks_device.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1604373917.1401203-7799-221460709672824/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.crypto.luks_device_payload_kewvgto3/ansible_community.crypto.luks_device_payload.zip/ansible_collections/community/crypto/plugins/modules/luks_device.py", line 711, in run_module
  File "/tmp/ansible_community.crypto.luks_device_payload_kewvgto3/ansible_community.crypto.luks_device_payload.zip/ansible_collections/community/crypto/plugins/modules/luks_device.py", line 426, in run_luks_create
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cipher": null,
            "device": "/dev/vda",
            "force_remove_last_key": false,
            "hash": null,
            "keyfile": null,
            "keysize": null,
            "label": null,
            "name": "test",
            "new_keyfile": null,
            "new_passphrase": null,
            "passphrase": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "remove_keyfile": null,
            "remove_passphrase": null,
            "state": "present",
            "type": "luks2",
            "uuid": null
        }
    },
    "msg": "luks_device error: Error while creating LUKS on /dev/vda: "
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

Non-logged output:
![image](https://user-images.githubusercontent.com/12296130/97947153-6f823b00-1d5a-11eb-8cc7-a28a8ab1ade2.png)
