### ISSUE TITLE
luks_device: Support sector size for luksFormat 

### ISSUE THREAD

**Issue by nilsmeyer** [ansible-collections/community.crypto#192]
##### SUMMARY
LUKS2 allows for using sector sizes larger than 512 bytes. This has performance advantages. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
luks_device

##### ADDITIONAL INFORMATION
Add an option, sector_size to luks_device. On formatting, this would use the --sector-size parameter to use a different sector size or fail when luks2 isn't being used. An additional challenge may be that luksFormat will only format a device if the device size dividable by the sector size, users will have to bear this in mind when dealing with underlying devices. 

```yaml
- name: Create LUKS container with a passphrase and 4096 bytes sector size
  community.crypto.luks_device:
    device: "/dev/loop0"
    state: "present"
    sector_size: 4096
    type: luks2
    passphrase: "foo"

```
