### ISSUE TITLE
Add signing key passphrase parameter to openssh_cert

### ISSUE THREAD

**Issue by Apreche** [ansible-collections/community.crypto#195]
##### SUMMARY
Allow the user to provide a passphrase to decrypt the signing key when using openssh_cert to create certs.

##### ISSUE TYPE
Not sure if this is a feature or a bug. On the one hand, none of the existing code is broken, per se, so it could be said this is a new feature. On the other hand, this is a pretty severe oversight that makes the module all but useless for anyone who encrypts their private keys, and who doesn't encrypt their private keys, especially a host_ca?

##### COMPONENT NAME
community.crypto.openssh_cert

##### ADDITIONAL INFORMATION

When using community.crypto.openssh_cert to sign a key, and the signing key is encrypted, it is required for the user to provide a passphrase to decrypt it. According to the documentation, community.crypto.openssh_cert has no way to provide this passphrase. When trying to use this module to sign a key using an encrypted ca key, the following error appears:

```
fatal: [23.239.9.7]: FAILED! => {"changed": false, "cmd": "/usr/bin/ssh-keygen -s /path/to/host_ca -h -I '' -n test.example.com -P '' /path/to/ssh_host_rsa_key.pub", "msg": "Load key \"/path/to/host_ca\": incorrect passphrase supplied to decrypt private key", "rc": 255, "stderr": "Load key \"/path/to/host_ca\": incorrect passphrase supplied to decrypt private key\r\n", "stderr_lines": ["Load key \"/path/to/host_ca\": incorrect passphrase supplied to decrypt private key"], "stdout": "", "stdout_lines": []}
```

I found this issue reported on the main ansible repository. It said the issue would be transferred to the community repository, but it doesn't seem to have made its way over here. I am doing that now.

[https://github.com/ansible/ansible/issues/66686](https://github.com/ansible/ansible/issues/66686)

Here is an example of how this could look after it is implemented.

```yaml
- name: Generate an OpenSSH host certificate that is valid forever and only for example.com and examplehost
  community.crypto.openssh_cert:
    type: host
    signing_key: /path/to/private_key
    signing_key_passphrase: "{{ passphrase }}"
    public_key: /path/to/public_key.pub
    path: /path/to/certificate
    valid_from: always
    valid_to: forever
    principals:
        - example.com
        - examplehost

```
