### ISSUE TITLE
Multiple OUs for CSR

### ISSUE THREAD

**Issue by oehlrich9** [ansible-collections/community.crypto#215]
##### SUMMARY
The openssl_csr module should support multiple OU fields for large companies.

```
openssl_csr:
    ...
    organizational_unit_name: 
       - "Engineering"
       - "Operations"
       - "Security"
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl_csr

##### ADDITIONAL INFORMATION
Big companies use multiple OU entries for a more specific assignment of the certificates which is compliant with X.509.
E.g.:
O="Company", OU="Engineering", OU="Operations", OU="Security"

This can not be covered with ansible right now

**Comment by MarkusTeufelberger** [comment]
If you have a more complex `subject`, then you can specify the subject directly:

```
openssl_csr:
  subject:
    O: Company
    OU:
      - Engineering
      - Operations
      - Security
```

Should work like this, from memory.
