### ISSUE TITLE
openssh_cert key type parameter

### ISSUE THREAD

**Issue by dgcampea** [ansible-collections/community.crypto#219]
##### SUMMARY

Add key type parameter (ssh-keygen -t arg).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.crypto.openssh_cert

**Comment by Ajpantuso** [comment]
Is there any more context to this request?
Key type (`-t`) is not a valid parameter for the commands executed by this module currently.
```bash
# Not executed by this module
ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa] [-N new_passphrase] [-C comment] [-f output_keyfile]
# Executed by this module
ssh-keygen -L [-f input_keyfile]
ssh-keygen -s ca_key -I certificate_identity [-h] [-U] [-D pkcs11_provider] [-n principals] [-O option] [-V validity_interval] [-z serial_number] file ...
```

**Comment by dgcampea** [comment]
> Is there any more context to this request?

Selecting which algorithm to use for ssh host certificates.

**Comment by Ajpantuso** [comment]
> > Is there any more context to this request?
> 
> Selecting which algorithm to use for ssh host certificates.

Do you have an example of the full `ssh-keygen` command with the options you need?

Just updating the below example from the module docs it is possible to specify both which algorithm would be used to sign the certificate via `signing_key` and which host key to sign via `public_key`.
```yaml
# Generate an OpenSSH host certificate that is valid for 32 weeks from now and will be regenerated
# if it is valid for less than 2 weeks from the time the module is being run
- name: Generate an OpenSSH host certificate with valid_from, valid_to and valid_at parameters
  community.crypto.openssh_cert:
    type: host
    signing_key: ca.key # The type of this key was already set at the time of generation
    public_key: /etc/ssh/ssh_host_rsa_key.pub
    path: /etc/ssh/ssh_host_rsa_key-cert.pub
    valid_from: +0s
    valid_to: +32w
    valid_at: +2w
    ```

**Comment by dgcampea** [comment]
> Do you have an example of the full `ssh-keygen` command with the options you need?

```shell
ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -C "" -N ""
```

**Comment by Ajpantuso** [comment]
> > Do you have an example of the full `ssh-keygen` command with the options you need?
> 
> ```shell
> ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -C "" -N ""
> ```

Gotcha.

This module's scope is limited to generating signed certificates for ssh public keys.

The appropriate module for generating a ed25519 key pair is _openssh_keypair_:
```yaml
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_ed25519_key
    type: ed25519
    comment: ""
```
