### ISSUE TITLE
Locally creating ecdsa key of size 521 results in "Sorry, try again." + freeze

### ISSUE THREAD

**Issue by GMTSE** [ansible-collections/community.crypto#251]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Attempting to(locally)  create an ecdsa key of size 521 with `openssh_keypair` displays "Sorry, train again." and freezes 

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.11.1] 
  config file = None
  configured module search path = ['/home/gmuller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gmuller/Python/Ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/gmuller/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gmuller/Python/Ansible/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux Mint / Python 3.8.5 / pip 21.1.2 

##### STEPS TO REPRODUCE

```yaml
- name: "ECDSA key error"
  hosts: monitorme
  remote_user: myuser
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

    - name: "Create SSH keys (LOCALLY)"
      openssh_keypair:
        state: present
        force: no
        regenerate: never
        path: ~/.ssh/monitorme
        type: ecdsa
        size: 521  # max value! (256/384/521)
      delegate_to: localhost  # execute locally, not on the inventory machines
      run_once: yes # run locally only once, not for each machine in the inventory
```

##### EXPECTED RESULTS

- Key should be generated
- Ansible playbook should continue, not freeze

##### ACTUAL RESULTS

- Key is not generated
- Playbook freezes

```paste below
TASK [Create SSH keys (LOCALLY)] *************************************************************
Sorry, try again.
^C [ERROR]: User interrupted execution
```

**Comment by Ajpantuso** [comment]
"Sorry, try again." is a sudo prompt.
Since you have `become: true` at the playbook level this task is attempting to run as root on the controller.
Try the following:
```yaml
   - name: "Create SSH keys (LOCALLY)"
      become: false 
      # become_user: myuser as well if you really wanted a keypair owned by your run id
      openssh_keypair:
        state: present
        force: no
        regenerate: never
        path: ~/.ssh/monitorme
        type: ecdsa
        size: 521
      delegate_to: localhost
      run_once: yes
```
