### ISSUE TITLE
add parameter to change starttls protocol

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.crypto#262]
##### SUMMARY

`get_certificate` failed when the `host` target is a mysql/mariadb/percona/proxysql host.

currently workaround is using `shell` with `openssl -starttls mysql` parameter.  

atm it is failing with 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get cert from some.mariadb.host:3306, error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)"}
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`get_certificate`

##### ADDITIONAL INFORMATION

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    DOMAIN: jedox.test.lekker.de
    TEAMS_WEBHOOK: "{{ lookup('env', 'TEAMS_WEBHOOK') }}"

  tasks:
    - name: fetch cert with shell
      shell: openssl s_client -starttls mysql -showcerts  -connect  some.mariadb.host:3306 | openssl x509 -noout -dates
      register: out

    - debug:
        var: out.stdout_lines[1].split("=")[1].split(" ")[0:5]| join("") | to_datetime('%b%d%H:%M:%S%Y')

    - name: "failed today"
      get_certificate:
          host: "{{ DOMAIN }}"
          port: 3306
      register: cert
```
