### ISSUE TITLE
Using umlauts in the CSR subject break idempotency

### ISSUE THREAD

**Issue by simontunnat** [ansible-collections/community.crypto#270]
I have issues using umlauts in a CSR.

Example:
```yaml
- name: "Create certificate signing request"
  community.crypto.openssl_csr:
    country_name: "DE"
    state_or_province_name: "Baden-Württemberg"
    ...
```

Leads to the following message when running the play for the FIRST time:
```
TASK [Create certificate signing request] ******************************************************
--- before
+++ after
...
+    "subject": {
+        "countryName": "DE",
+        "stateOrProvinceName": "Baden-W\u00fcrttemberg"
```

Leads to the following message when running the play for the SECOND or THIRD time:
```
TASK [Create certificate signing request] ******************************************************
changed: [somehost]
```

After this the CSR file has the same content but the last modified timestamp has changed.

This issue seems to be encoding related. When I encode the string "Baden-Württemberg" as "Baden-W\xC3\xBCrttemberg" in my play it works as intended.
