### ISSUE TITLE
community.crypto.openssh_cert with old ssh creates deprecated signatures and cannot override

### ISSUE THREAD

**Issue by brianmay** [ansible-collections/community.crypto#276]
##### SUMMARY

```
$ ssh panda07.pri 
check_host_cert: certificate signature algorithm ssh-rsa: signature algorithm not supported
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.crypto.openssh_cert

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /home/brian/.ansible.cfg
  configured module search path = ['/home/brian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

##### COLLECTION VERSION

```paste below

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 1.4.0
```

Have checked git, appears to have same problem.

##### STEPS TO REPRODUCE

Create and install ssh host certificate with:

```yaml
   - name: Generate an OpenSSH host certificate [rsa]                            
     community.crypto.openssh_cert:                                              
       type: host                                                                
       use_agent: yes                                                            
       signing_key: "/etc/ssh/ca.pub"                                            
       public_key: "/etc/ssh/ssh_host_rsa_key.pub"                               
       path: "/etc/ssh/ssh_host_rsa_key-cert.pub"                                
       valid_from: +0s                                                           
       valid_to: +52w                                                            
       valid_at: +1s                                                             
       force: yes     
```

##### EXPECTED RESULTS

ssh should accept host certificate.

##### ACTUAL RESULTS

ssh does not accept host certificate.

```paste below
$ ssh panda07.pri 
check_host_cert: certificate signature algorithm ssh-rsa: signature algorithm not supported
```

##### SOLUTION

Old versions of `ssh-keygen` need the following parameter `-t rsa-sha2-256`, but community.crypto.openssh_cert does not support passing this parameter.
