### ISSUE TITLE
 variable substitution is not working properly

### ISSUE THREAD

**Issue by charltonstanley** [ansible-collections/community.crypto#311]
##### SUMMARY
When creating or updating an account, standard variable substitution is not working for the `mailto` entry under the `contact` list.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.crypto.acme_account`

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
  config file = /home/username/svn/playground/server-dev/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

##### COLLECTION VERSION
My ansible version doesn't support `ansible-galaxy collection list`, however when i force install the module, i do get the following output which proves the collection version.
```paste below
$ ansible-galaxy collection install community.crypto --verbose --force
Using /home/username/svn/playground/server-dev/ansible.cfg as config file
Process install dependency map
Starting collection install process
Installing 'community.crypto:1.9.5' to '/home/username/.ansible/collections/ansible_collections/community/crypto'
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/username/svn/playground/server-dev/ansible.cfg) = ['/home/username/svn/playground/server-dev/inventory.yml']
DEFAULT_MANAGED_STR(/home/username/svn/playground/server-dev/ansible.cfg) = Ansible managed: modified on %Y-%m-%d %H:%M:%S
DEFAULT_ROLES_PATH(/home/username/svn/playground/server-dev/ansible.cfg) = ['/home/username/svn/playground/server-dev/shared_roles']
DEFAULT_STDOUT_CALLBACK(/home/username/svn/playground/server-dev/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/home/username/svn/playground/server-dev/ansible.cfg) = False
HOST_KEY_CHECKING(/home/username/svn/playground/server-dev/ansible.cfg) = False
INTERPRETER_PYTHON(/home/username/svn/playground/server-dev/ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

Amazon Linux 2
`uname -a` output
```
Linux hostname.domain 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

declare a variable that contains your email address
```yaml
account_email: email@validDomain.com
```
create/update an account using a task

```yaml
- name: Make sure account with the given email address exists. Create account if it doesn't exist
  become: true
  community.crypto.acme_account:
    account_key_src: "{{ account_private_key_path }}"
    state: present
    allow_creation: yes
    contact:
    - mailto: "{{ account_email }}" # <------ this is the line that generates the error
    acme_version: "{{ acme_version }}"
    acme_directory: "{{ acme_url }}"
    terms_agreed: yes
```

##### EXPECTED RESULTS

variable substitution works like it does for every other substituted variable, using the same syntax.

##### ACTUAL RESULTS

because there is a space between `mailto:` and `"{{ account_email }}"` an error is thrown.

```paste below
fatal: [server-dev]: FAILED! => changed=false 
  msg: 'ACME request failed for https://acme-staging-v02.api.letsencrypt.org/acme/acct/<redacted> with status 400. Error urn:ietf:params:acme:error:invalidEmail: "Unable to update account :: invalid contact".'
  other:
    http_status: 400
    http_url: https://acme-staging-v02.api.letsencrypt.org/acme/acct/<redacted>
    problem:
      detail: 'Unable to update account :: invalid contact'
      status: 400
      type: urn:ietf:params:acme:error:invalidEmail
    subproblems: []
```
the only way to fix this is to remove the space and remove the double quotes around the curly braces.

Change this:
```yaml
contact:
  - mailto: "{{ account_email }}"
```
to this:

```yaml
contact:
  - mailto:{{ account_email }}
```

Because of this deviation in how you have to reference the variable and because the error message gives you no indication that the space is actually causing the problem, it seems like this is a bug. I think the fix would be account for scenarios where a space is present between the colon and the start of the double quotes (when referencing a variable) or when specifying the raw email address as a string.

disclaimer: I'm new to ansible, and may not know what I'm talking about. :smile: 
Thanks for taking the time to review this; please let me know if you have any questions.
