### ISSUE TITLE
openssh_keypair module returns emtpy values in public_key and fingerprint when launched from tower 3.8.4

### ISSUE THREAD

**Issue by TheBlaide** [ansible-collections/community.crypto#323]
##### SUMMARY
When using the module openssh_keypair in tower, the pubic_key and fingerprint returned values are empty. but using from the CLI everything is ok

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.crypto.openssh_keypair

##### ANSIBLE VERSION

```paste below
ansible 2.9.25
  config file = /var/lib/awx/projects/rotate_ssh_key/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/var/lib/awx/projects/rotate_ssh_key/ansible.cfg) = ['/var/lib/awx/projects/rotate_ssh_key/inventory']
GALAXY_SERVER_LIST(/var/lib/awx/projects/rotate_ssh_key/ansible.cfg) = ['rh-certified_repo', 'community']
```

##### OS / ENVIRONMENT
RHEL 8.4
TOWER 3.8.4

##### STEPS TO REPRODUCE

```yaml
- name: Generate New Keypair on Tower
  openssh_keypair:
    path: '{{ ssh_key_path }}'
    owner: '{{ ssh_host_user }}'
    group: '{{ ssh_host_user }}'
    comment: '{{ ssh_key_comment }}'
    force: '{{ force_new_key }}'
  delegate_to: '{{ delegate_to_host }}'
  run_once: True
  register: newkey

- name: debug
  debug: 
    msg: '{{ newkey }}'

```

##### EXPECTED RESULTS

ok: [10.200.100.3] => {
    "msg": {
        "changed": false,
        "comment": "sv_ansible@tower.local",
        "failed": false,
        "filename": "/home/sv_ansible/.ssh/id_rsa",
        "fingerprint": "SHA256:1234567899XXXXXXXX",
        "public_key": "XXXXXXXXX",
        "size": 4096,
        "type": "rsa"
    }
}

##### ACTUAL RESULTS
when run from tower 3.8.4

```paste below
{
    "msg": {
        "changed": false,
        "size": 4096,
        "type": "rsa",
        "filename": "/home/sv_ansible/.ssh/id_rsa",
        "fingerprint": "",
        "public_key": {},
        "comment": "sv_ansible@tower.local",
        "failed": false
    },
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": null,
        "ansible_port": null,
        "ansible_user": "sv_ansible"
    }
}
```
