### ISSUE TITLE
Support content parameter for x509_certificate_info

### ISSUE THREAD

**Issue by michalmedvecky** [ansible-collections/community.crypto#346]
##### SUMMARY
x509_certificate_info could support `content` along `path`

Currently, only path to a file can be passed as an input, but what if I have the certificate already in a variable that I don't want to save to a file?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.crypto.x509_certificate_info

##### ADDITIONAL INFORMATION

Suggested usage:

```

- name: Fetch certificate info from a variable
  community.crypto.x509_certificate_info:
    content: "{{ certificate }}"
  register: out
```
