### ISSUE TITLE
luks_device: support for the cryptsetup resize command

### ISSUE THREAD

**Issue by InteNs** [ansible-collections/community.crypto#348]
##### SUMMARY
support for the cryptsetup resize command

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.crypto.luks_device

##### ADDITIONAL INFORMATION
our ansible playbook for an encrypted partition makes use of the resize feature of `community.general.parted` and `community.general.filesystem`.

`community.crypto.luks_device` supporting the resize option through `cryptsetup resize` will enable a fully online resize of the encrypted partition through Ansible.

```yaml
- name: Create partition
  community.general.parted:
    device: "/dev/{{luks_device.disk}}"
    number: 1
    fs_type: "{{luks_device.fs_type}}"
    part_end: "100%"
    resize: true
    state: present

- name: Setup luks device
  community.crypto.luks_device:
    device: "/dev/{{luks_device.disk}}1"
    state: "present"
    resize: true # <-- this would be fantastic :D
    cipher: "aes-cbc-essiv:sha256"
    hash: "ripemd160"
    keysize: 256
    passphrase: "xxxx"

- name: Create filesystem on luks device
  community.general.filesystem:
    device: "/dev/mapper/{{luks_device.disk}}1d"
    fstype: "{{luks_device.fs_type}}"
    resizefs: true
    opts: -L LUKS
```

**Comment by wejdross** [comment]
I'd also love to see such feature, meanwhile You can grab my setup to solve that issue:
```
---
- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present
    resize: yes

- name: resize pv to catch all changes
  shell: pvresize /dev/sdb1
  ignore_errors: true

- name: creating volume group
  lvg:
    vg: data-vg
    pvs: /dev/sdb1

- name: creating logical volume
  lvol:
    vg: data-vg
    lv: data-lv
    size: +100%FREE
    force: yes

- name: Create LUKS container with a passphrase
  community.crypto.luks_device:
    device: '/dev/data-vg/data-lv'
    state: 'present'
    name: data-luks
    passphrase: 'asd'

- name: Create LUKS container with a passphrase
  community.crypto.luks_device:
    device: '/dev/data-vg/data-lv'
    state: 'opened'
    name: data-luks
    passphrase: 'asd'

- name: resize pv to catch all changes
  shell: echo 'asd' | cryptsetup resize data-luks -

- name: resizefs
  shell: resize2fs /dev/mapper/data-luks

- name: Create directory data if does not exist
  file:
    path: /data
    state: directory
    mode: '0755'

- name: format the ext4 filesystem
  filesystem:
    fstype: ext4
    dev: /dev/mapper/data-luks

- name: mount the lv on /data
  mount:
    path: /data
    src: /dev/mapper/data-luks
    fstype: ext4
    state: mounted
```

maybe not the best, but automatically resize everything when I do changes in terraform, cheers!
