### ISSUE TITLE
openssh_keypair does not include comment in public_key field

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/community.crypto#411]
##### SUMMARY

In documentation of openssh_keypair, specifically in the "Return Values" section it has an example of `public_key`:
```
Sample:
ssh-rsa AAAAB3Nza(...omitted...)veL4E3Xcw== test_key
```
In this example the public key includes the comment `test_key`.  
But in reality the comment `test_key` is not included in the `public_key` return value.

This could also be a documentation issue - but I believe the comment should be included in the `public_key` return value.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssh_keypair

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/y/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /x/lib64/python3.6/site-packages/ansible
  ansible collection location = /y/.ansible/collections:/usr/share/ansible/collections
  executable location = /x/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.2.1
```

##### CONFIGURATION

```paste below
not relevant
```

##### OS / ENVIRONMENT

EL7

##### STEPS TO REPRODUCE

```yaml
- name: generate key
  community.crypto.openssh_keypair:
    comment: "key-2022-02-20"
    group: root
    mode: '0400'
    owner: root
    path: /root/key
    type: ed25519
  register: sshkey
```

##### EXPECTED RESULTS

`sshkey.public_key` should include the comment `key-2022-02-20` as is common and as is listed in documentation section "Return Values".

##### ACTUAL RESULTS

The return value `public_key` does not include the comment.

```paste below

```
