### ISSUE TITLE
Parameter to switch between Punycode and Unicode

### ISSUE THREAD

**Issue by hakong** [ansible-collections/community.crypto#426]
##### SUMMARY
It would be great to have a parameter to switch between Punycode and Unicode IDNs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
x509_certificate_info for example.

##### ADDITIONAL INFORMATION
Example with two domains:
- domain.com
- dömain.com (xn--dmain-jua.com)

I am comparing the SANs of a certificate to a list of SANs in a variable. If these two don't match, a new certificate has to be ordered.
The variable contains Punycode versions of an IDN (it has to for other reasons). Therefore, the comparison always fails and a new certificate is ordered every time.

```
- name: certificate | Register new certificate info and validity time
  community.crypto.x509_certificate_info:
    path: "{{ certificate_new_cert_path }}/{{ certificate_new_fullchain_name }}"
    valid_at:
      point_1: "{{ certificate_min_validity_time }}"
  register: new_fullchain_result

- name: certificate | Set sans_equal bool false if SANs don't match
  set_fact:
    sans_equal: false
  when:
    - "(new_fullchain_result.subject_alt_name | map('regex_replace', 'DNS:', '') | list | sort) != (certificate_san | sort)"
```
This will compare `domain.com,dömain.com` to `domain.com,xn--dmain-jua.com`.

I am aware of https://github.com/ansible/ansible/issues/11572#issuecomment-121079201. In my case the variable contains 10+ domains, a little less than half are IDNs.
