### ISSUE TITLE
community.crypto.openssh_keypair: Add an option to specify the number of key derivation function rounds used for ed25519 sshkeys 

### ISSUE THREAD

**Issue by 4wk-** [ansible-collections/community.crypto#449]
##### SUMMARY
I would like to be able to specify the **number of key derivation function rounds** used when generating an **ed25519 ssh key**, just like with the command: `ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519`

I am well aware that [this feature request have been discussed in the past](https://github.com/ansible/ansible/issues/66019) and it was closed because the `openssh_keypair` module wasn't able to handle passphrase back then. 
AFAIK, now the module **can** handle passphrases! 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.crypto.openssh_keypair

##### ADDITIONAL INFORMATION
This would drastically increase security of the generated sshkeys
 > The -a 100 option specifies 100 rounds of key derivations, making your key's password harder to brute-force.
[source](https://security.stackexchange.com/a/144044/177896)

**Example:**
```yaml
- name: Generate ssh keys
  community.crypto.openssh_keypair:
    path: /tmp/id_ed25519
    state: present
    type: ed25519
    kdf_rounds: 100
```
