### ISSUE TITLE
Getting the SAN of a certificate is retuning special characters.

### ISSUE THREAD

**Issue by LakshmiKell** [ansible-collections/community.crypto#465]
##### SUMMARY

When try to extract SAN information of a certificate is returning special characters. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.crypto.get_certificate:
##### ANSIBLE VERSION

```paste below
{
                            "asn1_data": "0s�\u001cftc-lbjbapp326.net�\u000eftc-lbjbapp326�\u0018jb-e2e3-01.net�\njb-e2e3-01�\u0017cams-e2e3.net�\u0004e2e3",
                            "critical": false,
                            "name": "subjectAltName"
                        },
                        {
                            "asn1_data": "\u0004\u0014���\u0000�q\u001f%�$ݯ�/�\u0016�R��",
                            "critical": false,
                            "name": "subjectKeyIdentifier"
                        },
                        {
                            "asn1_data": "0\u0016�\u0014Zq�b4�$!����\rT�\u000f?�\u0016�",
                            "critical": false,
                            "name": "authorityKeyIdentifier"
                        },
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

All Linux 

##### STEPS TO REPRODUCE

Connect to server over a specific host and port and extract the certificate and parse the cert and get all of the values that cert has like Subject, extensions,( SAN) 

```yaml
- name: Display CSV file only host and port 
  community.crypto.get_certificate:
    host: "{{ item.HOSTNAME }}"
    port: "{{ item.PORT }}"
  run_once: true
  register: cert
  delegate_to: localhost
  ignore_errors: yes
  loop: "{{ results.list }}"

- name: get cert information
  debug:
    msg:  "Certificate subject {{ item.subject.CN }}, extensions values {{''.join(item.extensions[1].asn1_data)  }} , validity {{ (item.not_before | to_datetime('%Y%m%d%H%M%SZ')) }}"
  when: item.failed != True
  register: cert_details
  ignore_errors: yes
  loop: "{{ cert.results }}"

- name: display cert_details
  debug: var=cert_details
```

##### EXPECTED RESULTS

Below list is expected without any special characters 
ftc-lbjbapp326.net,ftc-lbjbapp326,jb-e2e3-01.net,jb-e2e3-01,cams-e2e3.net

##### ACTUAL RESULTS

0s�\u001cftc-lbjbapp326.net�\u000eftc-lbjbapp326�\u0018jb-e2e3-01.net�\njb-e2e3-01�\u0017cams-e2e3.net�\u0004e2e

```paste below

```
