### ISSUE TITLE
community.crypto.x509_certificate_pipe hangs

### ISSUE THREAD

**Issue by bfrk** [ansible-collections/community.crypto#471]
##### SUMMARY
community.crypto.x509_certificate_pipe hangs, apparently waiting for something to happen but without telling me what. The tasks in question (adapted from https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html#use-the-ca-to-sign-a-certificate):

```
- name: Create private key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/{{inventory_hostname}}.key

- name: Create certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/ssl/private/{{inventory_hostname}}.key
  register: csr

- name: Sign certificate with our CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: /srv/files/ssl/certs/acs_ca_crt.pem
    ownca_privatekey_path: /srv/files/ssl/private/acs_ca_key.pem
  delegate_to: localhost
  register: certificate
```
I get:
```
TASK [common : Create private key] ****************************************************
ok: [bullseye.acc.bessy.de]

TASK [common : Create certificate signing request (CSR)] ******************************
changed: [bullseye.acc.bessy.de]

TASK [common : Sign certificate with our CA] ******************************************
```
and then it hangs there. I tried to increase verbosity (-vvvvv) but it doesn't print any useful information to debug this issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- community.crypto.x509_certificate_pipe

##### ANSIBLE VERSION
```
ansible 2.10.8
```

##### COLLECTION VERSION
```
# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 1.4.0  
```

##### OS / ENVIRONMENT
```
> uname -a
Linux ansible 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
```
