### ISSUE TITLE
privatekey_content always says "Wrong passphrase provided for private key"

### ISSUE THREAD

**Issue by Warwind006** [ansible-collections/community.crypto#489]
##### SUMMARY
When I use the privatekey_content option it always says "Wrong passphrase provided for private key". 
I have already tried several keys all were without passphrase. If I use the same key as a file with privatekey_path it works

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.crypto.openssl_csr

##### ANSIBLE VERSION

```paste below
ansible 2.9.20
python version = 3.9.13
```

##### OS / ENVIRONMENT

Target System: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

##### STEPS TO REPRODUCE

```yaml
- name: Generate an OpenSSL Certificate Signing Request with Subject information
    community.crypto.openssl_csr:
      path: "/tmp/test.csr"
      privatekey_content: "-----BEGIN PRIVATE KEY----- XXXX -----END PRIVATE KEY-----"
      common_name: "server1.int"
```

##### EXPECTED RESULTS

The CSR is created without searching for a password like the privatekey_path option

##### ACTUAL RESULTS

A password is searched for when creating the CSR, although the private key does not have one.

 ```yaml
The full traceback is:
  File "/tmp/ansible_community.crypto.openssl_csr_payload_yci62fpg/ansible_community.crypto.openssl_csr_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_csr.py", line 337, in main
  File "/tmp/ansible_community.crypto.openssl_csr_payload_yci62fpg/ansible_community.crypto.openssl_csr_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_csr.py", line 281, in generate
  File "/tmp/ansible_community.crypto.openssl_csr_payload_yci62fpg/ansible_community.crypto.openssl_csr_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/csr.py", line 307, in generate_csr
    self._ensure_private_key_loaded()
  File "/tmp/ansible_community.crypto.openssl_csr_payload_yci62fpg/ansible_community.crypto.openssl_csr_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/csr.py", line 214, in _ensure_private_key_loaded
    raise CertificateSigningRequestError(exc)
fatal: [server1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "authority_cert_issuer": null,
            "authority_cert_serial_number": null,
            "authority_key_identifier": null,
            "backup": false,
            "basic_constraints": null,
            "basic_constraints_critical": false,
            "common_name": "server1.int",
            "content": null,
            "country_name": null,
            "create_subject_key_identifier": false,
            "crl_distribution_points": null,
            "delimiter": null,
            "digest": "sha256",
            "directory_mode": null,
            "email_address": null,
            "extended_key_usage": null,
            "extended_key_usage_critical": false,
            "follow": false,
            "force": false,
            "group": null,
            "key_usage": null,
            "key_usage_critical": false,
            "locality_name": null,
            "mode": null,
            "name_constraints_critical": false,
            "name_constraints_excluded": null,
            "name_constraints_permitted": null,
            "ocsp_must_staple": false,
            "ocsp_must_staple_critical": false,
            "organization_name": null,
            "organizational_unit_name": null,
            "owner": null,
            "path": "/tmp/test.csr",
            "privatekey_content": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "privatekey_passphrase": null,
            "privatekey_path": null,
            "regexp": null,
            "remote_src": null,
            "return_content": false,
            "select_crypto_backend": "auto",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "state_or_province_name": null,
            "subject": null,
            "subject_alt_name": null,
            "subject_alt_name_critical": false,
            "subject_key_identifier": null,
            "subject_ordered": null,
            "unsafe_writes": null,
            "use_common_name_for_san": true,
            "version": 1
        }
    },
    "msg": "Wrong passphrase provided for private key"
}
```
