### ISSUE TITLE
Support format PKCS8 in community.crypto.openssh_keypair.private_key_format

### ISSUE THREAD

**Issue by DonBower** [ansible-collections/community.crypto#510]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssh_keypair

##### ADDITIONAL INFORMATION

Allow users to set private_key_format to PKCS8 when using opensshbin.
Default of auto could select the older PKCS1 format.

A converter was discussed in #332, but this would create the key in the desired format without needing to convert.
Currently, https://concourse-ci.org requires keys in this format, and I am sure there are others.

Keys can be created with the command `ssh-keygen -m PKCS8 -t rsa -b 4096 -f worker_key`

```yaml
- name: Generate RSA 4096 Bit Keys in PKCS8 format
  become: true
  community.crypto.openssh_keypair:
    path: "/etc/concourse/{{ item }}"
    size: 4096
    type: rsa
    format: PKCS8
    owner: "{{ concourseUser }}"
    group: concourse
  with_items:
    - session_signing_key
    - tsa_host_key
    - worker_key
```

**Comment by MarkusTeufelberger** [comment]
Concourse seems to require PEM though, not PKCS8? https://concourse-ci.org/concourse-generate-key.html#generating-the-keys --> `ssh-keygen -t rsa -b 4096 -m PEM -f ./worker_key`

The conversion module already exists, I'm not sure if this is the right way forward to integrate that work into `openssh_keypair` again, but I'm also not too thrilled about the conversion part. Are there other examples of widespread use for PKCS8 OpenSSH keypairs and does Concourse actually use them (e.g. do you have a link to their docs where they require it)?

**Comment by DonBower** [comment]
When I used the default (PKCS1) I got an error, found that same error here:
https://github.com/concourse/concourse/discussions/6888
which implied I needed PKCS8.

When I regenerated the keys with the -m PKCS8, concourse started without complaint.

I do not know of other services that require PKCS8.

I agree this seems overly restrictive. to that end:
https://github.com/concourse/rfcs/discussions/134

**Comment by felixfontein** [comment]
#511 implements a way to set the format. (It does not offer conversion functionality.)

**Comment by DonBower** [comment]
I'm not sure your PR fixes the issue.
While it does now allow for the selection of pkcs8, it still creates a key with `-----BEGIN OPENSSH PRIVATE KEY-----`
Further, the key material does not begin with `MIIC...BADANB` as described by https://superuser.com/questions/1515261/how-to-quickly-identify-ssh-private-key-file-formats

my task:
```yaml
- name: Generate RSA 4096 Bit Keys
      become: true
      community.crypto.openssh_keypair:
        path: "/etc/concourse/test_key"
        size: 4096
        type: rsa
        private_key_format: pkcs8
        owner: concourse
        group: concourse
        mode: '0644'
```
produced an openssh private key. (`-----BEGIN OPENSSH PRIVATE KEY-----`).

**Comment by felixfontein** [comment]
@Ajpantuso maybe the module should warn or fail if that option is used with the wrong backend?

**Comment by DonBower** [comment]
Success!
I did have to add `regenerate: full_idempotence` though.

```yaml
- name: Generate RSA 4096 Bit Keys
  become: true
  community.crypto.openssh_keypair:
    path: "/etc/concourse/{{ item }}"
    size: 4096
    type: rsa
    backend: cryptography
    private_key_format: pkcs8
    regenerate: full_idempotence
    owner: "{{ concourseUser }}"
    group: concourse
    mode: '0644'
  with_items:
    - session_signing_key
    - tsa_host_key
    - worker_key
```

Thank you for the fast resolution.
I look forward to the PR promoted to production.
