### ISSUE TITLE
x509_certificate_pipe fails in --check mode

### ISSUE THREAD

**Issue by jdelafon** [ansible-collections/community.crypto#563]
##### SUMMARY
`x509_certificate_pipe` fails with "Wrong passphrase provided for private key" when ran in --check mode. Without check mode, the playbook runs fine so the password is correct.
It all happens in memory, based on values also in memory, so the task has no reason to fail. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.crypto.x509_certificate_pipe

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bcv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/bcv/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, Aug 23 2022, 09:14:58) [GCC 10.2.1 20210110] (/usr/local/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection       Version
---------------- -------
community.crypto 2.5.0
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/xxxx/.vault_pass.txt
GALAXY_SERVER(/etc/ansible/ansible.cfg) = https://xxxx/nexus/repository/galaxy.ansible.com/
```

##### OS / ENVIRONMENT
Debian GNU/Linux 11 (Docker)

##### STEPS TO REPRODUCE

Choose a "password". Run a playbook with the following tasks, adding the --check flag :
```yaml
- name: "Generate private key (in-memory)"
  community.crypto.openssl_privatekey_pipe:
      type: "RSA"
      size: "4096"
      passphrase: "{{ password }}"
      cipher: "auto"
  register: privatekey

- name: "Generate certificate signing request (CSR) (in-memory)"
  community.crypto.openssl_csr_pipe:
      privatekey_content: "{{ privatekey.privatekey }}"
      privatekey_passphrase: "{{ password }}"
      common_name: "xxxx"
      organization_name: "xxxx"
      organizational_unit_name: "xxxx"
      use_common_name_for_san: false
      key_usage:
        - keyCertSign
        - cRLSign
  register: csr

- name: "Generate self-signed certificate (in-memory)"
  community.crypto.x509_certificate_pipe:
      provider: selfsigned
      privatekey_content: "{{ privatekey.privatekey }}"
      privatekey_passphrase: "{{ password }}"
      csr_content: "{{ csr.csr }}"
  register: cert
```

##### EXPECTED RESULTS
No error, generates a certificate in memory. At least the error message should indicate that some value is missing, not that the password is wrong.

##### ACTUAL RESULTS
Fails with "Wrong passphrase provided for private key".

Without --check :
```
bcv@ansible-engine:~/ansible-deploy (vto)$ ansible-playbook -i inventories/dd playbooks/test.yml -e password=1234

PLAY [Test] ********************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [hddvto01]

TASK [Generate private key (in-memory)] ****************************************************************************************************
changed: [hddvto01]

TASK [Generate certificate signing request (CSR) (in-memory)] ******************************************************************************
changed: [hddvto01]

TASK [Generate self-signed certificate (in-memory)] ****************************************************************************************
changed: [hddvto01]

PLAY RECAP *********************************************************************************************************************************
hddvto01                   : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
In --check mode :
```
bcv@ansible-engine:~/ansible-deploy (vto)$ ansible-playbook -i inventories/dd playbooks/test.yml -e password=1234 --check

PLAY [Test] ********************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [hddvto01]

TASK [Generate private key (in-memory)] ****************************************************************************************************
changed: [hddvto01]

TASK [Generate certificate signing request (CSR) (in-memory)] ******************************************************************************
changed: [hddvto01]

TASK [Generate self-signed certificate (in-memory)] ****************************************************************************************
fatal: [hddvto01]: FAILED! => {"changed": false, "msg": "Wrong passphrase provided for private key"}

PLAY RECAP *********************************************************************************************************************************
hddvto01                   : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
