### ISSUE TITLE
keyout and csr in same module

### ISSUE THREAD

**Issue by fred-gb** [ansible-collections/community.crypto#574]
Bonjour, 👋🏻 

Maybe I make mistake by post here and if that the case, I'm sorry... 

##### SUMMARY
An openssl command can generate a private key and csr.

##### ADDITIONAL INFORMATION
I tried to follow this tutorial from Hashicorp:
[Secure Consul Agent Communication with Encryption and Certificates](https://developer.hashicorp.com/consul/tutorials/security-operations/tls-encryption-openssl-secure#step-1-create-server-certificate-signing-requests)

And I would like to do this with ansible module.

But I'm stuck at first step. To convert in ansible module this command:
```
openssl req -new -newkey rsa:2048 -nodes -keyout server1.dc1.consul.key -out server1.dc1.consul.csr -subj '/CN=server.dc1.consul'
```
I don't find how to generate a key and csr associate.

In next steps, sign the csr, It uses a CA. And after, put file path in configuration files.
```
    "tls": {
        "defaults": {
            "ca_file": "/etc/ssl/hashistack/hashistack-ca.pem",
            "cert_file": "/etc/ssl/hashistack/consul/server.dc1.consul.crt",
            "key_file": "/etc/ssl/hashistack/consul/server.dc1.consul.key",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": true,
            "verify_outgoing": true
        },
```

But when I try with ansible, I cannot boot my consul server.
```
==> Failed to load cert/key pair: tls: private key does not match public key
```
So, my dev playbook:
```
- name: Installation Hashistack
  hosts: sandbox2.dev
  become: yes
  vars:
    hashistack_deploy_dc_name: "dc1"
  tasks:
    - name: block certificate
      block:
### ANSIBLE CA
        - name: Create private key for CA
          community.crypto.openssl_privatekey:
            path: /tmp/hashistack/hashistack-ca-key.pem

        - name: Generate an OpenSSL Certificate Signing Request for CA
          community.crypto.openssl_csr:
            path:  /tmp/hashistack/hashistack-ca.csr
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            common_name: hashistack CA

        - name: Create self-signed CA certificate from CSR for CA
          community.crypto.x509_certificate:
            path: /tmp/hashistack/hashistack-ca.pem
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            provider: selfsigned

        - name: Hashistack | Create TLS directories on ansible controller to generate TLS
          ansible.builtin.file:
            path: "/tmp/hashistack/{{ item }}"
            state: directory
            mode: '0755'
            recurse: yes
          loop:
          - consul
          - vault
          - nomad
          delegate_to: localhost
          become: no

### CERTS

        - name: Create private key for CA
          community.crypto.openssl_privatekey:
            path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.key
          loop:
          - consul
          - vault
          - nomad

        - name: Generate an OpenSSL Certificate Signing Request for Consul Server
          community.crypto.openssl_csr:
            path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.csr
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            subject_alt_name: '{{ item.subject_alt_name }}'
          loop:
          - { dir: "consul", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.{{ hashistack_deploy_dc_name }}.consul"}
          - { dir: "vault", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.{{ hashistack_deploy_dc_name }}.vault"}
          - { dir: "nomad", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.global.nomad,DNS:server.{{ hashistack_deploy_dc_name }}.nomad"}

        - name: Generate an OpenSSL certificate signed with your own CA certificate
          community.crypto.x509_certificate:
            path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.crt
            csr_path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.csr
            ownca_path: /tmp/hashistack/hashistack-ca.pem
            ownca_privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            provider: ownca
          loop:
          - consul
          - vault
          - nomad

      delegate_to: localhost
      become: no

    - name: Hashistack | Create TLS directories
      ansible.builtin.file:
        path: "/etc/ssl/hashistack/{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
      - consul
      - vault
      - nomad

    - name: Hashistack | Copy certificates on server
      ansible.builtin.copy:
        src: "/tmp/hashistack/{{ item.dir | default(omit)  + '/'  }}{{ item.certificate }}"
        dest: "/etc/ssl/hashistack/{{ item.dir | default(omit)  + '/' }}{{ item.certificate }}"
      loop:
      - { dir: "", certificate: "hashistack-ca.pem" }      
      - { dir: "consul", certificate: "server.{{ hashistack_deploy_dc_name }}.consul.key" }
      - { dir: "consul", certificate: "server.{{ hashistack_deploy_dc_name }}.consul.crt" }
      - { dir: "vault", certificate: "server.{{ hashistack_deploy_dc_name }}.vault.key" }
      - { dir: "vault", certificate: "server.{{ hashistack_deploy_dc_name }}.vault.crt" }
      - { dir: "nomad", certificate: "server.{{ hashistack_deploy_dc_name }}.nomad.key" }
      - { dir: "nomad", certificate: "server.{{ hashistack_deploy_dc_name }}.nomad.crt" }

```  

Do I forgot something? Or does it exist in ansible openssl module to do this?

Help!

**Comment by fred-gb** [comment]
Thanks a lot @felixfontein , it's better! 
But new command, new error. It feels like never ending story.

```
2023-02-10T21:07:19.434+0100 [WARN]  agent: error getting server health from server: server=sandbox2 error="rpc error getting client: failed to get conn: x509: certificate signed by unknown authority (possibly because of \"x509: invalid signature: parent certificate cannot sign this kind of certificate\" while trying to verify candidate authority certificate \"serial:174034365502283252922673948843781393411613501107\")"
2023-02-10T21:07:19.434+0100 [ERROR] agent.server.rpc: failed to read byte: conn=from=192.168.64.65:52477 error="remote error: tls: bad certificate"
```

It's too late for today, I will try to find tomorrow if it's come from Consul configuration or certificates generation.

Thanks!

**Comment by felixfontein** [comment]
You probably need to mark the CA certificate as a proper CA certificate, and add things like
```
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
```
to the `openssl_csr` call for the CA certificate. (I copied that from https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html#set-up-the-ca)

**Comment by fred-gb** [comment]
Hello,

Thanks again @felixfontein.

I follow this before. Without success. Each times, `unknown authority`. 

I modified and adapt with yout example and this example: [Josh-Tracy/Kubernetes-Home-Lab](https://github.com/Josh-Tracy/Kubernetes-Home-Lab/blob/main/roles/certificates/tasks/main.yml).

My news tasks:
```
# ### ANSIBLE CA
    - name: block certificate
      block:
        - name: Create private key for CA
          community.crypto.openssl_privatekey:
            path: /tmp/hashistack/hashistack-ca-key.pem

        - name: Generate an OpenSSL Certificate Signing Request for CA
          community.crypto.openssl_csr:
            path:  /tmp/hashistack/hashistack-ca.csr
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            common_name: hashistack
            use_common_name_for_san: false
            basic_constraints: 
            - 'CA:TRUE'
            basic_constraints_critical: True
            key_usage: 
              - cRLSign 
              - keyCertSign
            key_usage_critical: True

        - name: Create self-signed CA certificate from CSR for CA
          community.crypto.x509_certificate:
            path: /tmp/hashistack/hashistack-ca.pem
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            provider: selfsigned

      delegate_to: localhost
      become: no

    - name: Hashistack | Create TLS directories on ansible controller to generate TLS
      ansible.builtin.file:
        path: "/tmp/hashistack/{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
      - consul
      - vault
      - nomad
      delegate_to: localhost
      become: no

# ### CERTS

    - name: block certificate
      block:
        - name: Create private key
          community.crypto.openssl_privatekey:
            path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.key
          loop:
          - consul
          - vault
          - nomad

        - name: Generate an OpenSSL Certificate Signing Request for Consul Server
          community.crypto.openssl_csr:
            path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.csr
            privatekey_path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.key
            common_name: "*.{{ hashistack_deploy_dc_name }}.{{ item.dir }}"
            subject_alt_name: '{{ item.subject_alt_name }}'
            basic_constraints: "CA:FALSE"
            basic_constraints_critical: True
            key_usage:
              - digitalSignature
              - keyEncipherment
            key_usage_critical: True
            extended_key_usage:
              - serverAuth
              - clientAuth
          loop:
          - { dir: "consul", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.dc1.consul"}
          - { dir: "vault", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.{{ hashistack_deploy_dc_name }}.vault"}
          - { dir: "nomad", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.global.nomad,DNS:server.{{ hashistack_deploy_dc_name }}.nomad"}

      delegate_to: localhost
      become: no

    - name: Generate an OpenSSL certificate signed with your own CA certificate
      community.crypto.x509_certificate:
        path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.crt
        csr_path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.csr
        ownca_path: /tmp/hashistack/hashistack-ca.pem
        ownca_privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
        provider: ownca
      loop:
      - consul
      - vault
      - nomad
      delegate_to: localhost
      become: no
```

And error:
```
2023-02-16T15:54:50.934+0100 [WARN]  agent: error getting server health from server: server=sandbox2 error="rpc error getting client: failed to get conn: x509: certificate signed by unknown authority (possibly because of \"x509: invalid signature: parent certificate cannot sign this kind of certificate\" while trying to verify candidate authority certificate \"serial:575999800495383141452815482901312394614841063029\")"
2023-02-16T15:54:50.934+0100 [ERROR] agent.server.rpc: failed to read byte: conn=from=192.168.64.65:51803 error="remote error: tls: bad certificate"
```

I don't understand the serial number in log. I don't know if it related to my issue.

I don't know what I missed.

Thanks if you can help me!

**Comment by MarkusTeufelberger** [comment]
You need to actually use the CSR you're creating.

**Comment by fred-gb** [comment]
Hi,
Sorry, I think it's what I did 🤨 

```
            path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.csr
[...]
            csr_path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.csr
```

**Comment by MarkusTeufelberger** [comment]
The one for the CA is missing:

        - name: Create self-signed CA certificate from CSR for CA
          community.crypto.x509_certificate:
            path: /tmp/hashistack/hashistack-ca.pem
            privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
            provider: selfsigned

**Comment by fred-gb** [comment]
Many Thanks @MarkusTeufelberger !
It works now! 👍🏻 

I don't know how I can miss that!
I read again and again and don't see.

This is my lastest working tasks:
```
- name: Hashistack | Block Certificate Authority
  block:
    - name: Hashistack | Create private key for CA
      community.crypto.openssl_privatekey:
        path: /tmp/hashistack/hashistack-ca-key.pem

    - name: Hashistack | Generate an OpenSSL Certificate Signing Request for CA
      community.crypto.openssl_csr:
        path:  /tmp/hashistack/hashistack-ca.csr
        privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
        common_name: hashistack
        use_common_name_for_san: false
        basic_constraints:
        - 'CA:TRUE'
        basic_constraints_critical: True
        key_usage:
          - cRLSign
          - keyCertSign
        key_usage_critical: True

    - name: Hashistack | Create self-signed CA certificate from CSR for CA
      community.crypto.x509_certificate:
        path: /tmp/hashistack/hashistack-ca.pem
        csr_path: /tmp/hashistack/hashistack-ca.csr
        privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
        provider: selfsigned

  delegate_to: localhost
  become: no

- name: Hashistack | Block certificate for Hashistack components
  block:
    - name: Hashistack | Create private key
      community.crypto.openssl_privatekey:
        path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.key
      loop:
      - consul
      - vault
      - nomad

    - name: Hashistack | Generate an OpenSSL Certificate Signing Request for components
      community.crypto.openssl_csr:
        path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.csr
        privatekey_path: /tmp/hashistack/{{ item.dir }}/server.{{ hashistack_deploy_dc_name }}.{{ item.dir }}.key
        common_name: "*.{{ hashistack_deploy_dc_name }}.{{ item.dir }}"
        subject_alt_name: '{{ item.subject_alt_name }}'
        basic_constraints: "CA:FALSE"
        basic_constraints_critical: True
        key_usage:
          - digitalSignature
          - keyEncipherment
        key_usage_critical: True
        extended_key_usage:
          - serverAuth
          - clientAuth
      loop:
      - { dir: "consul", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.dc1.consul"}
      - { dir: "vault", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.{{ hashistack_deploy_dc_name }}.vault"}
      - { dir: "nomad", subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.global.nomad,DNS:server.{{ hashistack_deploy_dc_name }}.nomad"}

  delegate_to: localhost
  become: no

- name: Hashistack | Generate an OpenSSL certificate signed with your own CA certificate
  community.crypto.x509_certificate:
    path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.crt
    csr_path: /tmp/hashistack/{{ item }}/server.{{ hashistack_deploy_dc_name }}.{{ item }}.csr
    ownca_path: /tmp/hashistack/hashistack-ca.pem
    ownca_privatekey_path: /tmp/hashistack/hashistack-ca-key.pem
    provider: ownca
  loop:
  - consul
  - vault
  - nomad
  delegate_to: localhost
  become: no

- name: Hashistack | Create TLS directories
  ansible.builtin.file:
    path: "/etc/ssl/hashistack/{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
  - consul
  - vault
  - nomad
```

Thanks again! And if you have other good advice on this method, I'm interested! 🤗
