### ISSUE TITLE
`openssl_csr_pipe` generates content that's censored (not just the logs)

### ISSUE THREAD

**Issue by huyz** [ansible-collections/community.crypto#587]
##### SUMMARY

If I use `openssl_csr_pipe`, I get a resulting `registered_var.csr` that's garbled with censored `*****` parts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.crypto.openssl_csr_pipe`

##### ANSIBLE VERSION

From MacPorts:
```paste below
❯ ansible --version
ansible [core 2.14.1]
  config file = /Users/huyz/.ansible.cfg
  configured module search path = ['/Users/huyz/.ansible/plugins/modules', '/opt/local/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/huyz/.ansible/collections:/opt/local/share/ansible/collections
  executable location = /opt/local/bin/ansible
  python version = 3.11.2 (main, Feb 23 2023, 00:28:39) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
❯ ansible-galaxy collection list community.crypto

# /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.9.0

# /Users/huyz/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.10.0
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/Users/huyz/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/huyz/.ansible.cfg) = ~/.cache/ansible/facts
CACHE_PLUGIN_TIMEOUT(/Users/huyz/.ansible.cfg) = 86400
CONFIG_FILE() = /Users/huyz/.ansible.cfg
DEFAULT_GATHERING(/Users/huy/.ansible.cfg) = smart
DEFAULT_MANAGED_STR(/Users/huyz/.ansible.cfg) = vim: set nomodifiable : Ansible-managed: Do NOT edit this file manually! See template source instead ({file}) or use `:set modifiable` to force.
DEFAULT_VAULT_ID_MATCH(/Users/huyz/.ansible.cfg) = true
DISPLAY_SKIPPED_HOSTS(/Users/huyz/.ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/Users/huzy/.ansible.cfg) = /Users/huyz/.ansible
```

##### OS / ENVIRONMENT

Controller: macOS 13.3 (Ventura, ARM)
Target: self (via `connection: local`)

##### STEPS TO REPRODUCE

```yaml
    # Per https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ path }}/private/{{ name }}.pem"
        privatekey_passphrase: "{{ _ca_passphrase }}"
        common_name: My CA
        use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: _ca_csr
      no_log: false
      become: true

    - name: Create self-signed X.509 certificate
      community.crypto.x509_certificate:
        path: "{{ path }}/certs/{{ name }}.crt"
        csr_content: "{{ _ca_csr.csr }}"
        #csr_path: "{{ path }}/csr/{{ name }}.csr"
        privatekey_path: "{{ path }}/private/{{ name }}.pem"
        privatekey_passphrase: "{{ _ca_passphrase }}"
        provider: selfsigned
        mode: '0644'
      become: true

```

##### EXPECTED RESULTS

No error, like the `community.crypto.openssl_csr` equivalent, which works just fine for me.

##### ACTUAL RESULTS

```paste below
TASK [Create self-signed X.509 certificate] **********************************************************************************************************************************************************************************************************
task path: /Users/huyz/git/ansible/tasks/gen_x509_selfsigned_ca.yml:105
The full traceback is:
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/x****************9_certificate.py", line 4********8, in main
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate.py", line 332, in select_backend
    return provider.create_backend(module, backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate_selfsigned.py", line 183, in create_backend
    return SelfSignedCertificateBackendCryptography(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate_selfsigned.py", line 66, in __init__
    self._ensure_csr_loaded()
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate.py", line 146, in _ensure_csr_loaded
    self.csr = load_certificate_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.crypto.x****************9_certificate_payload_8sfqj87z/ansible_community.crypto.x****************9_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/support.py", line 226, in load_certificate_request
    raise OpenSSLObjectError(exc)
fatal: [hmax]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "acme_accountkey_path": null,
            "acme_chain": false,
            "acme_challenge_path": null,
            "acme_directory": "https://acme-v********2.api.letsencrypt.org/directory",
            "attributes": null,
            "backup": false,
            "csr_content": "-----BEGIN CERTIFICATE REQUEST-----\nMIIEiTCCAnECAQAwEjEQMA4GA1UEAwwHaG********ldCBDQTCCAiIwDQYJKoZIhvcNAQEB\nBQADggIPADCCAgoCggIBAMjH3KmL3nyJKhHJEzq4ENpiuaN6G8+gcAQQVJ94BDFe\n2+/OAUnRtsMm6CmHSPDFjafAiDMLA9z8Pht********ZBEdEFGjCXYPkJU9Xja1t3cD1dfs\nXHKNnOFHusEizodtENVkzXc9/pGHR11utNXM********umLF6cA99Rhj9wUtS6m********mQA+PUc\n7s8t********VSQ8kjK/vssGXtr7ofVTmoH********HrOkitS8JuMcHy6mK4k9n21zKkyrI89bDLA\nbs9Pt********a********QjqbDBYZjoiqGmQ/24********sRbizcst6WXBUvzjs1tJI********TkOKleXQurHQSGq\nr7eZSBAqAgjUrU9LLYic+KlEgQ3/Q********xp6nzMnLIBA+6T6AzQO6nMsfW3zRivOJbO\nb919pWjhoQFBuNpt//iLQnNrxWtnPyC********DGr4q9r+K********WBzSHwaeYi8f********Ru9QMiqSM\n3rkZWNoJVUEZgg+WVk7xv3l3BpLgAGBWhSSbzq+NUter3w********JPGOpLUUjVtLKTTgQ\nN1qJOl7bYWUBAf********VQReTAI9OdkIhkLm3DsmXlR********LLc********DgLAGd7+K8DzxB4ZU3UlG\nC4A1pBbat+bYUDV2EDofAlWfDIl3meAKQwMnkMWCLELGsUtkZTj6LewrDNGhvLGm\nu8HvWAsD7QaQQvk4CB********2ZrHJUMZOuQZs1SU46F3QcTw+oCG********I4/********JJ+X1KUwiCrJ\nAgMBAAGgMjAwBgkqhkiG9w********BCQ4xIzAhMA4GA1UdDwEB/wQEAwICBDAPBgNVHRMB\nAf8EBTADAQH/MA********GCSqGSIb3DQEBCwUAA4ICAQB8y1********Jf/w+2u7AqoUc79TSdfFi\nE********jrXhB********jgo4j+X9peEFTNaWtztRqkJQ6quhAGak3IcrR3/wM********BBMRPhf********QfhdhK\ngSJMS43uT316c8/oJjJmSy/ysf2SbP18x9791NLJUFXZufpZazNMY8v3UeiVV4X7\nRSTXXrDHJQpg2+AsM********iggC28XygpZwnSS********pYhQFYnYBQE2uP6c6c7q7A/Z********xKeoT\neui3Em+Wp4uTZGLwOlb********I********B4zr11vrsKGpUX********UmM6xOpZJKff6ADT8OHq/VO1PIz\nV1CMwOzP6/qN3cSRJzgo4mMpM14gJf********jk********BiPogRek77RTxlit6HkSH4bgKHvwOa\nxyy/9DAbb6NHKsHfEKbSRry********w6DsGfGvQQ1mu6J482rO64GIBuotfimeLfHI92Z2\n2fHu********vmUcOj2+EDrOdteGvpvJfmqZYCESKeFflBkzny4BaHvvkpTg+********F********JD9M8hD\nFIA9darhl4nGocEjRMYYCYleqP6MbdAo7flqWTOSiOFI9mQX********H6RQUOSSxjNzNNP\nT/XPZJTaDI1YRZKV********DA8LRby6i+r3AJb21LBDHvi********m1XWSkU9G242uigrzElnNpH\n9IfbKw********w********RPYBBZWZIr/4KWKj+s36sUcgux6uNRkBdVN********Pw********NJIQnR2********ukjHivgP\nqk********7/GJiWgz3ouon********A==\n-----END CERTIFICATE REQUEST-----\n",
            "csr_path": null,
            "entrust_api_client_cert_key_path": null,
            "entrust_api_client_cert_path": null,
            "entrust_api_key": null,
            "entrust_api_specification_path": "https://cloud.entrust.net/EntrustCloud/documentation/cms-api-2.1.********.yaml",
            "entrust_api_user": null,
            "entrust_cert_type": "STANDARD_SSL",
            "entrust_not_after": "+36********d",
            "entrust_requester_email": null,
            "entrust_requester_name": null,
            "entrust_requester_phone": null,
            "force": false,
            "group": null,
            "ignore_timestamps": true,
            "mode": "********644",
            "ownca_content": null,
            "ownca_create_authority_key_identifier": true,
            "ownca_create_subject_key_identifier": "create_if_not_provided",
            "ownca_digest": "sha2********6",
            "ownca_not_after": "+36****************d",
            "ownca_not_before": "+********s",
            "ownca_path": null,
            "ownca_privatekey_content": null,
            "ownca_privatekey_passphrase": null,
            "ownca_privatekey_path": null,
            "ownca_version": 3,
            "owner": null,
            "path": "/var/root/cabinet/ssl/certs/root-ca.crt",
            "privatekey_content": null,
            "privatekey_passphrase": "{'changed': False, 'rc': ********, 'stderr': '', 'stdout': '********', 'start': '2********23-********4-********3 ********4:19:49.********74871', 'stop': '2********23-********4-********3 ********4:19:********4.9********1************************', 'delta': ********, 'echo': False, 'user_input': '********', 'failed': False}",
            "privatekey_path": "/var/root/cabinet/ssl/private/root-ca.pem",
            "provider": "selfsigned",
            "return_content": false,
            "select_crypto_backend": "auto",
            "selevel": null,
            "selfsigned_create_subject_key_identifier": "create_if_not_provided",
            "selfsigned_digest": "sha2********6",
            "selfsigned_not_after": "+36****************d",
            "selfsigned_not_before": "+********s",
            "selfsigned_version": 3,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "unsafe_writes": false
        }
    },
    "msg": "Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidByte(34, 42))"
}
```
