### ISSUE TITLE
Add custom SNI support for get_certificate

### ISSUE THREAD

**Issue by blablup** [ansible-collections/community.crypto#595]
##### SUMMARY
Add an option to support custom sni names, different from host

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
get_certificate

##### ADDITIONAL INFORMATION
For cluster use to directly connect to the cluster Server but still retrieve the correct certificate, it would be useful to add an option for a different sni name to connect to. 
 
```yaml
- name: "Get a cert from an cluster node"
  get_certificate:
    host: "clusternode01.mydomain.test"
    sni: "www.mydomain.test"
    port: 443
```

I can create a patch/mr if appreciated and helpful
