### ISSUE TITLE
Different modes for private/public keys with `openssh_keypair`

### ISSUE THREAD

**Issue by lonix1** [ansible-collections/community.crypto#632]
##### SUMMARY

The `openssh_keypair` sets the same mode for both private and public keys.

So `mode: '0600'` will set that mode for both keys. Typically the private key has `600` and the public has `644` (if not, then ssh won't read it, so I need to add another task to fix the permissions).

##### ISSUE TYPE
- Feature Idea
Another attribute, e.g. `mode_public`, which sets the mode just for the public key.

##### COMPONENT NAME

openssh_keypair

##### ADDITIONAL INFORMATION

As above.

```yml
- community.crypto.openssh_keypair:
  type: ed25519
  path: /home/me/.ssh/id_ed25519_foo
  mode: '0600'
  mode_public: '0644'             # <------------------
```
