### ISSUE TITLE
x509_crl does not support non-integer serial_number

### ISSUE THREAD

**Issue by p3lim** [ansible-collections/community.crypto#687]
##### SUMMARY

Using `x509_crl` to generate a CRL where `serial_number` of certificates are non-integer (e.g. `11:22:33:44:55...`) will fail because it tries to convert this value to an integer.

Non-integer serial numbers are widespread and used for most modern PKIs (just take a look at github.com's certificate, or this collection's own `openssl_csr`/`openssl_csr_pipe`), and should be supported.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

x509_crl

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/runner/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.16.2

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.15.1
```

##### CONFIGURATION

```paste below
empty/irrelevant
```

##### OS / ENVIRONMENT

Ubuntu 22.04

##### STEPS TO REPRODUCE

```yaml
- community.crypto.x509_crl:
    path: /srv/ca.crl
    privatekey_path: /srv/pki/ca.key
    privatekey_passphrase: xxx # from vault
    issuer: xxx
    next_update: '+12w'
    revoked_certificates:
      - serial_number: '11:22:33:44:55:...'
        reason: 'privilege_withdrawn'
        revocation_date: 20231201000000Z
```

##### EXPECTED RESULTS

CRL being generated at /srv/ca.crl

##### ACTUAL RESULTS

```paste below
fatal: [box]: FAILED! => {"changed": false, "msg": "argument 'serial_number' is of type <class 'str'> found in 'revoked_certificates'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"}
```
