### ISSUE TITLE
Add PEM format to the openssh_keypair module

### ISSUE THREAD

**Issue by Aalmain** [ansible-collections/community.crypto#724]
##### SUMMARY

The ssh-keygen tool has the capability of creating ssh-keys in the PEM format. Although this is not a common format, there are instances where it is required

##### ISSUE TYPE
Add the "PEM" format to the lost of formats under "private_key_format" in the "community.crypto.openssh_keypair"

##### COMPONENT NAME
Module:  community.crypto.openssh_keypair
Parameter: private_key_format

##### ADDITIONAL INFORMATION
This would allow a more standard process to create ssh keys in the PEM format. There are applications that require this format. 

An example is the Yugabyte Anywhere control plain communication to the Yugabyte Anywhere database nodes for universe deployments and updates.

```
- name: Generate an OpenSSH keypair for Yugabyte 
  community.crypto.openssh_keypair:
    path: /home/yugabyte/.ssh/id_ssh_pem
    prvate_key_format: pem
```
