### ISSUE TITLE
LUKS devices not getting encrypted properly

### ISSUE THREAD

**Issue by StoffelCPR** [ansible-collections/community.crypto#845]
##### SUMMARY

I'm trying to roll out luksEncryption onto disks and either get stuck or just an OK: and left without encryption

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

luks_device

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.7]
  config file = /home/stoffel/Projects/disks/ansible.cfg
  configured module search path = ['/home/stoffel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stoffel/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/stoffel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.0
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/stoffel/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.23.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 1.4.0
```

##### CONFIGURATION

```paste below
ANY_ERRORS_FATAL(/home/stoffel/Projects/disk/ansible.cfg) = False
CONFIG_FILE() = /home/stoffel/Projects/disk/ansible.cfg
DEFAULT_FORKS(/home/stoffel/Projects/disk/ansible.cfg) = 25
DEFAULT_HOST_LIST(/home/stoffel/Projects/disk/ansible.cfg) = ['/home/stoffel/Projects/disk/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/stoffel/Projects/disk/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/stoffel/Projects/disk/ansible.cfg) = ['/home/stoffel/Projects/disk/roles']
DEFAULT_STDOUT_CALLBACK(/home/stoffel/Projects/disk/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/stoffel/Projects/disk/ansible.cfg) = /home/stoffel/Projects/disk/.vault_pass
DISPLAY_SKIPPED_HOSTS(/home/stoffel/Projects/disk/ansible.cfg) = False
HOST_KEY_CHECKING(/home/stoffel/Projects/disk/ansible.cfg) = False
HOST_PATTERN_MISMATCH(/home/stoffel/Projects/disk/ansible.cfg) = ignore
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Target system is a ubuntu-22.04 server.

##### STEPS TO REPRODUCE

Let this run, it will result in the ansible module to try and encrypt the first drive, it will never fail it's stuck endlessly, `CTRL + C` once you're bored and tired of waiting and simply try again, the previously started encryption will now show "ok" but checking on the VM they're not encrypted. repeat untill all drives show "ok" none are actually encrypted.

if you switch from `passphrase: "test"` to `new_passphrase: "test"` or remove `passhphrase` completely then it will not get stuck but just run through and say "ok" for all devices but not one is encrypted afterwards.

```yaml
# HOST VARS:
ansible_host: 10.0.0.5
host_fqdn: "system1.hogwarts.internal"
hostname: system1

ansible_user: ansible
proxmox_virtualized: true

additional_disks:
  - path: "/etc/gitlab"
    vg_name: "vg_gitlabetc"
    lv_name: "lv_gitlabetc"
    pvs: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
  - path: "/opt/gitlab"
    vg_name: "vg_gitlabopt"
    lv_name: "lv_gitlabopt"
    pvs: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2"
  - path: "/var/opt/gitlab"
    vg_name: "vg_gitlabvaropt"
    lv_name: "lv_gitlabvaropt"
    pvs: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi3"
  - path: "/var/log/gitlab"
    vg_name: "vg_gitlablogs"
    lv_name: "lv_gitlablogs"
    pvs: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi4"
```

```yaml
---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create volume groups
      community.general.lvg:
        vg: "{{ item.vg_name }}"
        pvs: "{{ item.pvs }}"
        pvresize: true
      with_items: 
        - "{{ additional_disks }}"
    - name: Create logical volumes
      community.general.lvol:
        vg: "{{ item.vg_name }}"
        lv: "{{ item.lv_name }}"
        size: +100%FREE
      with_items: 
        - "{{ additional_disks }}"
    - name: Setup secure LUKS encryption
      community.crypto.luks_device:
        device: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
        type: luks2
        passphrase: "testing"
        pbkdf:
          algorithm: "argon2id"
          iteration_time: 2000
        keysize: 256
        hash: sha256
        cipher: "aes-xts-plain64:sha256"
        state: "present"
      with_items:
        - "{{ additional_disks }}"
```

##### EXPECTED RESULTS

I expect the module to either encrypt the disk partitions or fail in ansible

##### ACTUAL RESULTS

Either gets stuck or just reports "ok" without doing anything.
