### ISSUE TITLE
Harica ACME fails

### ISSUE THREAD

**Issue by arjandekker** [ansible-collections/community.crypto#923]
Hi,

i'm trying to get the Harica CA working with ACME with EAB.
I keeps getting errors which i'm unable to solve.

This part seems to work:

```
    - name: Perform ACME with EAB with private key, get acct URI
      community.crypto.acme_account:
        account_key_src: "{{ data_dir }}/{{ account_key_name }}.pem"
        acme_directory: "{{ acme_dir_url }}"
        state: present
        terms_agreed: true
        acme_version: "2"
        contact:
          - "mailto: xxxx@xxxxx.xx"
        external_account_binding:
          alg: "HS256"
          key: "{{ eab_key }}"
          kid: "{{ eab_kid }}"
        allow_creation: false
      register: acct_registration
```

this gives me the account_uri:
https://acme-v02.harica.gr/acme/........

but the first acme_certificate run fails and i have no idea why:

```
    - name: acme run 1
      community.crypto.acme_certificate:
        account_uri: "{{ acct_registration.account_uri }}"
        acme_version: 2
        acme_directory: "{{ acme_dir_url }}"
        account_key_src: "{{ data_dir }}/{{ account_key_name }}.pem"
        csr: "{{ data_dir }}/{{ cert_cn }}.csr"
        dest: "{{ data_dir }}/{{ cert_cn }}.pem"
        challenge: "no challenge"
        remaining_days: 7
        terms_agreed: true
        account_email: "xxxxxx@xxxxxx.xxx"
      no_log: false

```
which gives me the following error:
File ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/acme.py\", line 397, in send_signed_request\nAttributeError: 'str' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",
    "rc": 1

Any idea how to solve or debug this issue?

Thanks in advance.

Arjan

**Comment by arjandekker** [comment]
Hi,

thanks for your answer.

The collection version is:
community.crypto                         2.26.3

ansible version:
core 2.18.6

I tried your potential sollutions, but still the same error:
```
    - name: get acct URI
      community.crypto.acme_account:
        account_key_src: "{{ data_dir }}/{{ account_key_name }}.pem"
        acme_directory: "{{ acme_dir_url }}"
        state: present
        acme_version: "2"
        contact:
          - "mailto: xxxx@xxxxx.xx"
        external_account_binding:
          alg: "HS256"
          key: "{{ eab_key }}"
          kid: "{{ eab_kid }}"
      register: acct_registration

    - name: acme step 1
      community.crypto.acme_certificate:
        account_uri: "{{ acct_registration.account_uri }}"
        acme_version: 2
        acme_directory: "{{ acme_dir_url }}"
        account_key_src: "{{ data_dir }}/{{ account_key_name }}.pem"
        csr: "{{ data_dir }}/{{ cert_cn }}.csr"
        dest: "{{ data_dir }}/{{ cert_cn }}.pem"
        challenge: "no challenge"
        remaining_days: 7
        modify_account: false
```
Full stack trace:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py", line 107, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.crypto.plugins.modules.acme_certificate', init_globals=dict(_module_fqn='ansible_collections.community.crypto.plugins.modules.acme_certificate', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py", line 1083, in <module>
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py", line 1043, in main
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py", line 676, in __init__
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/account.py", line 285, in setup_account
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/account.py", line 205, in get_account_data
  File "/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/acme.py", line 397, in send_signed_request
AttributeError: 'str' object has no attribute 'get'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1750876940.8077223-447460-248964508663540/AnsiballZ_acme_certificate.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.crypto.plugins.modules.acme_certificate', init_globals=dict(_module_fqn='ansible_collections.community.crypto.plugins.modules.acme_certificate', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py\", line 1083, in <module>\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py\", line 1043, in main\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/modules/acme_certificate.py\", line 676, in __init__\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/account.py\", line 285, in setup_account\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/account.py\", line 205, in get_account_data\n  File \"/tmp/ansible_community.crypto.acme_certificate_payload_yn1o6_ep/ansible_community.crypto.acme_certificate_payload.zip/ansible_collections/community/crypto/plugins/module_utils/acme/acme.py\", line 397, in send_signed_request\nAttributeError: 'str' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",
    "rc": 1
}

Greets,

Arjan
