### ISSUE TITLE
openssh_cert: Idempotency and random serials

### ISSUE THREAD

**Issue by s-hamann** [ansible-collections/community.crypto#96]
##### SUMMARY
When creating new certificates, I want my serial numbers to be unique and that's about all. Uniqueness is required for the use with KRLs.
Uniqueness can be achieved by managing state or by assigning random serials with sufficient entropy (OpenSSH supports 64 bit integers). Since the former is cumbersome, I'd like to go with random serials. However, that does not currently seem to be possible without regenerating certificates.

For example, consider the following (incomplete) task:
```yaml
- openssh_cert:
    valid_from: always
    valid_to: +7d
    valid_at: +1d
```

Running this task generates a certificate. Running it twice still only generates one certificate. Running it again in a week regenerates the certificate. This seems to me what most people would want, except that the serial is always `0`.
I can set the serial to a random value:
```yaml
- openssh_cert:
    valid_from: always
    valid_to: +7d
    valid_at: +1d
    serial: "{{ 2**64 | random }}"
```

This task would (almost) always regenerate the certificate, since the serial number changes on each invocation. A `seed` for `random` does not help, since it can not ensure that the serial is constant until the expiry date is less than `valid_at`. 

According to https://github.com/ansible/ansible/pull/54653#pullrequestreview-220861479 there is some sense behind the choice of comparing serial numbers on the idempotency check. Unfortunately, I can not figure it out by myself and the comment does not elaborate on this.

Am I simply doing it wrong? Are users supposed to track and manage serial numbers manually?
If not, I suggest, that the serial number check should be made optional in `is_valid` or removed completely, if there is no valid use case for it.
Removing the check would be easiest but may break some use case I am not currently aware of. Making it optional would require a new parameter, which feels like cluttering the interface to me.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/modules/openssh_cert.py

##### ADDITIONAL INFORMATION
If someone gives me a hint on what would be acceptable behaviour, I can make a pull request.j

**Comment by felixfontein** [comment]
In general, Ansible modules should be idempotent: if you specify information which is the same as the object you're working on, they should not be modified, but if you specify something that's different (like a different serial number), it will be modified. That's why the current behavior is at it is.

I understand that this is not what's always needed. In this case, there are multiple possibilities:
1. Introduce a special value `"random"`, which accepts any existing serial number, but picks a random one when generating a new certificate.
2. Have an option to disable idempotency except in some cases. The big question here is what kind of choices should be available so that this makes sense.
3. Provide an option to configure idempotency more granulary. As an example, see the `comparisons` option of `docker_container` (https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#parameter-comparisons): it allows to configure which option sould be compared how. This looks a bit like overkill for this module, though.
4. Provide a `openssh_cert_info` module and make the user do their own idempotency tests. (I.e. call info module, and if cert does not exist, or does not satisfy some conditions, use `openssh_cert` with `force: yes` to (re-)generate.)

@MarkusTeufelberger @Shaps @resmo @ctrufan any opinions / ideas / suggestions on this? I guess the same questions are interesting for the other modules as well.

**Comment by vasdee** [comment]
@felixfontein  I'm facing this issue right now. I'm trying to migrate a pre-existing certificate generation tool under ansible control by retrofitting the keys, csrs and x509 certs attributes to ansible parameters. It's mostly going ok, but i do hit the odd problem with the serial number mismatch causing the certificate to be regenerated. 

In my use case it would be great to have an optional parameter called `serial_number` that accepts an integer (or hex) and defaults to the current randomly generated behaviour.

For what it is worth, I'm using the ownca options of x509_certificate

**Comment by felixfontein** [comment]
@vasdee Are you talking about `x509_certifiate` or about `openssh_cert`? The former does not allow to specify the serial and won't check it for idempotence, while the latter allows to specify it and uses it for idempotence. I'm really not sure what you mean with `but i do hit the odd problem with the serial number mismatch causing the certificate to be regenerated.`.

**Comment by vasdee** [comment]
apologies, got crypto overload at the moment, i meant the `x509_certificate` module. 

It's interesting you say that it doesn't check for idempotence though. When i'm using RSA and the Cryptography backend it seems to ignore it but my problem seems to only occur with ECC based certificates. I will look into it further and raise another ticket with examples if need be. Again, apologies for the misread

**Comment by s-hamann** [comment]
Just in case anyone else stumbles on this, here is my workaround. It first runs `openssh_cert` without a serial in check mode and only if that would change (i.e. (re-)generate) the certificate, runs the same task again, but with a random serial. Less cumbersome than I had anticipated :wink:

```yaml
- name: 'check SSH host key certficate validity'
  openssh_cert: &task_openssh_cert_sign_key
    type: host
    identifier: "{{ inventory_hostname }}"
    path: "{{ host_key_path.dest | regex_replace('\\.pub$', '-cert.pub') }}"
    signing_key: "{{ sshd_host_ca_key }}"
    public_key: "{{ host_key_path.dest }}"
    principals: "{{ sshd_cert_principals }}"
    state: present
    valid_from: "{{ now(fmt='-%Hh%Mm%Ss') }}"
    valid_to: "{{ '%Y-%m-%d' | strftime(now().timestamp() | int + sshd_cert_validity | int * 86400) }}"
    valid_at: "+{{ sshd_cert_min_validity }}d"
  loop: "{{ _fetch_host_keys.results }}"
  loop_control:
    loop_var: host_key_path
  register: _check_host_keys
  connection: local
  become: false
  check_mode: true

- name: 'sign SSH host keys'
  openssh_cert:
    <<: *task_openssh_cert_sign_key
    serial_number: "{{ 2**64 | random }}"
  loop: "{{ _fetch_host_keys.results }}"
  loop_control:
    loop_var: host_key_path
  when: "_check_host_keys.results | selectattr('filename', '==', host_key_path.dest | regex_replace('\\.pub$', '-cert.pub')) | first is changed"
  connection: local
  become: false
```
